version: '3.9'
services:
  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo-dev
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo-dev-admin
      ME_CONFIG_MONGODB_URL: mongodb://root:mongo-dev@mongo:27017/
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: devpass4444
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: devMSSQLpass123
    ports:
      - 1433:1433
  redis:
    image: redis/redis-stack:6.2.6-v6
    volumes:
      - redis:/data
    ports:
      - 6379:6379
      - 8001:8001
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    volumes:
      - azurite:/data
volumes:
  psql:
    external: true
  mongo:
    external: true
  redis:
    external: true
  rabbitmq:
    external: true
  azurite:
    external: true
